on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  hello:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - run: echo $GITHUB_EVENT_NAME
      - run: echo ${{ github.event.inputs.huh }}
      - id: step1
        run: echo "::set-output name=test::hello"

  hmm:
    needs: hello
    if: ${{needs.hello.outputs.output1 == 'hello yo'}}
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event_name  == 'workflow_dispatch' }}
        run: echo woot

  okay:
    if: ${{ github.event_name  == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo otaay
