on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_EVENT_NAME
      - run: echo ${{ github.event.inputs.huh }}

  hmm:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ env.GITHUB_EVENT_NAME  == 'workflow_dispatch' }}
        run: echo woot

  okay:
    if: ${{ env.GITHUB_EVENT_NAME  == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo otaay
