on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]
    tags: [practice-*]

jobs:
  hello:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - run: echo $GITHUB_EVENT_NAME
      - run: echo ${{ github.event.inputs.huh }}
      - id: step1
        run: echo "::set-output name=test::hello"
      - run: echo $GITHUB_REF
      - run: echo $GITHUB_SHA
      - uses: actions/cache@v2
        id: cache-ephemeral
        with:
          path: ephemeral
          key: some-cache-key
      - name: create ephemeral file
        if: steps.cache-ephemeral.outputs.cache-hit != 'true'
        run: echo "yooo" > ephemeral
      - name: use composite action
        uses: ./.github/actions/greeting
        with:
          who-to-greet: "Gandalf"

  aw:
    runs-on: ubuntu-latest
    needs: hello
    steps:
      - run: exit 1

  hmm:
    needs: hello
    if: ${{needs.hello.outputs.output1 == 'hello yo'}}
    runs-on: ubuntu-latest
    steps:
      - run: echo woot

  letsSee:
    needs: hmm
    runs-on: ubuntu-latest
    steps:
      - run: echo ayyy

  okay:
    if: ${{ github.event_name  == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo otaay
