on: 
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_EVENT_NAME
      - run: echo ${{ github.event.inputs.huh }}

  hmm:
    runs-on: ubuntu-latest
    steps:
      - run: echo woot
        if: ${{ env.GITHUB_EVENT_NAME }} == 'workflow_dispatch'