on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]
    tags: [practice-*]

jobs:
  hello:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - run: echo $GITHUB_EVENT_NAME
      - run: echo ${{ github.event.inputs.huh }}
      - id: step1
        run: echo "::set-output name=test::hello"
      - run: echo $GITHUB_REF
      - run: echo $GITHUB_SHA
      - run: echo "//registry.npmjs.org/:_authToken=$GITHUB_SHA" >> hmm
      - run: cat hmm

  hmm:
    needs: hello
    if: ${{needs.hello.outputs.output1 == 'hello yo'}}
    runs-on: ubuntu-latest
    steps:
      - run: echo woot

  letsSee:
    needs: hmm
    runs-on: ubuntu-latest
    steps:
      - run: echo ayyy

  okay:
    if: ${{ github.event_name  == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo otaay
